default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: user
  password: 123

development:
  <<: *default
  database: pedidoapp_development

test:
  <<: *default
  database: pedidoapp_test

production:
  <<: *default
  database: pedidoapp_production
